### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libbinder.so" not found

### ISSUE THREAD

**Issue by kingking888** [Pangu-Immortal/KeepAlivePerfect#2]
`E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.boolbird.keepalive:resident, PID: 23900
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libbinder.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.boolbird.keepalive.NativeKeepAlive.<clinit>(NativeKeepAlive.java:28)
        at com.boolbird.keepalive.KeepAliveProcessImpl$1.run(KeepAliveProcessImpl.java:103)`

**Comment by Pangu-Immortal** [comment]
有两个分支。
